#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := test_bench

include $(PWD)/../../mk/esp_playground_init.mk
include $(IDF_PATH)/make/project.mk
